version: '3.8'

services:
  app:
    build:
      context: .

    image: dormgo
    container_name: api
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=<your_password>
    ports:
      - "8002:1433"
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"
