name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  actions: write

env:
  ASPNETCORE_ENVIRONMENT: Development

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Ensure Docker is available
        run: docker version

      - name: Set up environment limits for SQL Server container
        run: |
          sudo sysctl -w vm.max_map_count=262144
          sudo sysctl -w fs.file-max=65536

      - name: Restore dependencies
        run: |
          cd src/DormGO
          dotnet restore

      - name: Build
        run: |
          cd src/DormGO
          dotnet build --no-restore

      - name: Run Integration Tests with Retry
        run: |
          cd tests/DormGO.Tests
          for i in {1..3}; do
            dotnet test --verbosity normal && break || sleep 10
          done
