name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  actions: write
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
               
      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Pull MSSQL image
        run: docker pull mcr.microsoft.com/mssql/server:2022-latest
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: |
          cd src/DormGO
          dotnet restore
      - name: Build
        run: |
          cd src/DormGO
          dotnet build --no-restore
      - name: Test
        run: |
          dotnet test
      - name: Upload DormGO.Tests.exe
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: DormGO.Tests.exe
          path: tests/DormGO.Tests/bin/Debug/net8.0/DormGO.Tests.exe