name: CI/CD

on:
  push:
    branches:
      - main
    paths:
      - ./src/server/IdentityApiAuth/**
      - .github/workflows/release.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build ./src/server/IdentityApiAuth/IdentityApiAuth.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ./src/server/IdentityApiAuth/IdentityApiAuth.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dormgo'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        env:
          ConnectionStrings__IdentityConnection: ${{ secrets.DB_CONNECTION_STRING }}
          EmailSettings__MailServer: 'smtp.gmail.com'
          EmailSettings__MailPort: 587
          EmailSettings__SenderName: 'dormgo-project'
          EmailSettings__FromEmail: 'sanzar30062000@gmail.com'
          EmailSettings__Password: ${{ secrets.EMAILSETTINGS_PASSWORD }}